basePath: /api
host: localhost:8080
info:
  contact: {}
  description: API Server for Budget Buddy Application
  title: Budget Buddy API
  version: "1.0"
paths: {}
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
